// [["AF", "93",
//     "Afghanistan"],
//      ["AL", "355",
//     "Albania",],
//      ["DZ", "213",
//     "Algeria",],
//      ["AS", "1684", "American Samoa"],
//       ["AD", "376", "Andorra"],
//        ["AO", "244", "Angola"],
//        ["AI", "1264",
//     "Anguilla"], 
//     ["AQ", "672",
//     "Antartica"],["AG", "1268",
//      "Antigua & amp;Barbuda"],["AR", "54",
//     "Argentina"],
//    , "[AM", "374",
//     "Armenia"],
//    , "[AW", "297",
//     "Aruba"],
//    , "[AU", "61",
//     "Australia"],
//    , "[AT", "43",
//     "Austria"],
//    , "[AZ", "994",
//     "Azerbaijan"],
//    , "[BS", "1242",
//     "Bahamas"],
//    , "[BH", "973",
//     "Bahrain"],
//    , "[BD", "880",
//     "Bangladesh"],
//    , "[BB", "1246",
//     "Barbados"],
//    , "[BY", "375",
//     "Belarus"],
//    , "[BE", "32",
//     "Belgium"],
//    , "[BZ", "501",
//     "Belize"],
//    , "[BJ", "229",
//     "Benin"],
//    , "[BM", "1441",
//     "Bermuda"],
//    , "[BT", "975",
//     "Bhutan"],
//    , "[BO", "591",
//     "Bolivia"],
//    , "BA", "38[7",
//     Bosnia & amp; "Herzegovina"],
//    , "[BW", "267",
//     "Botswana"],
//    , "[BR", "55",
//     "Brazil"],
//    , "IO", "24[6",
//     British India Ocean "Terrirory"],
//    , "VG", ["1284",
//     British Virgin "Islands"],
//    , "[BN", "673",
//     "Brunei"],
//    , "[BG", "359",
//     "Bulgaria"],
//    , "BF[", "226",
//     Burkina "Faso"],
//    , "[BI", "257",
//     "Burundi"],
//    , "[KH", "855",
//     "Cambodia"],
//    , "[CM", "237",
//     "Cameroon"],
//    , "[CA", "1",
//     "Canada"],
//    , "CV", ["238",
//     Cape Verde "Islands"],
//    , "KY[", "1345",
//     Cayman "Islands"],
//    , "CF", ["236",
//     Central African "Republic"],
//    , "[TD", "235",
//     "Chad"],
//    , "[CL", "56",
//     "Chile"],
//    , "[CN", "86",
//     "China"],
//    , "CX[", "61",
//     Christmas "Island"],
//    , "CC[", "61",
//     Cocos "Islands"],
//    , "[CO", "57",
//     "Colombia"],
//    , "[KM", "269",
//     "Comoros"],
//    , "CK[", "682",
//     Cook "Islands"],
//    , "CR[", "506",
//     Costa "Rica"],
//    , "[HR", "385",
//     "Croatia"],
//    , "[CU", "53",
//     "Cuba"],
//    , "[CW", "599",
//     "Curacao"],
//    , "CY", ["90",
//     Cyprus - "North"],
//    , "CY", ["357",
//         Cyprus - "South"],
//    , "CZ[", "420",
//     Czech "Republic"],
//    , "CD", "24[3",
//     Democratic Republic of "Congo"],
//    , "[DK", "45",
//     "Denmark"],
//    , "[DJ", "253",
//     "Djibouti"],
//    , "[DM", "1809",
//     "Dominica"],
//    , "DO[", "1809",
//     Dominican "Republic"],
//    , "TL[", "670",
//     East "Timor"],
//    , "[EC", "593",
//     "Ecuador"],
//    , "[EG", "20",
//     "Egypt"],
//    , "SV[", "503",
//     El "Salvador"],
//    , "GQ[", "240",
//     Equatorial "Guinea"],
//    , "[ER", "291",
//     "Eritrea"],
//    , "[EE", "372",
//     "Estonia"],
//    , "[ET", "251",
//     "Ethiopia"],
//    , "FK[", "500",
//     Falkland "Islands"],
//    , "FO[", "298",
//     Faroe "Islands"],
//    , "[FJ", "679",
//     "Fiji"],
//    , "[FI", "358",
//     "Finland"],
//    , "[FR", "33",
//     "France"],
//    , "GF[", "594",
//     French "Guiana"],
//    , "PF[", "689",
//     French "Polynesia"],
//    , "[GA", "241",
//     "Gabon"],
//    , "[GM", "220",
//     "Gambia"],
//    , "[GE", "7880",
//     "Georgia"],
//    , "[DE", "49",
//     "Germany"],
//    , "[GH", "233",
//     "Ghana"],
//    , "[GI", "350",
//     "Gibraltar"],
//    , "[GR", "30",
//     "Greece"],
//    , "[GL", "299",
//     "Greenland"],
//    , "[GD", "1473",
//     "Grenada"],
//    , "[GP", "590",
//     "Guadeloupe"],
//    , "[GU", "671",
//     "Guam"],
//    , "[GT", "502",
//     "Guatemala"],
//    , "[GG", "44",
//     "Guernsey"],
//    , "[GN", "224",
//     "Guinea"],
//    , "GW[", "245",
//     Guinea - "Bissau"],
//    , "[GY", "592",
//     "Guyana"],
//    , "[HT", "509",
//     "Haiti"],
//    , "[HN", "504",
//     "Honduras"],
//    , "HK[", "852",
//     Hong "Kong"],
//    , "[HU", "36",
//     "Hungary"],
//    , "[IS", "354",
//     "Iceland"],
//    , "[IN", "91",
//     "India"],
//    , "[ID", "62",
//     "Indonesia"],
//    , "[IR", "98",
//     "Iran"],
//    , "[IQ", "964",
//     "Iraq"],
//    , "[IE", "353",
//     "Ireland"],
//    , "IM", ["44",
//     Isle of "Man"],
//    , "[IL", "972",
//     "Israel"],
//    , "[IT", "39",
//     "Italy"],
//    , "CI[", "225",
//     Ivory "Coast"],
//    , "[JM", "1876",
//     "Jamaica"],
//    , "[JP", "81",
//     "Japan"],
//    , "[JE", "44",
//     "Jersey"],
//    , "[JO", "962",
//     "Jordan"],
//    , "[KZ", "7",
//     "Kazakhstan"],
//    , "[KE", "254",
//     "Kenya"],
//    , "[KI", "686",
//     "Kiribati"],
//    , "[XK", "383",
//     "Kosovo"],
//    , "[KW", "965",
//     "Kuwait"],
//    , "[KG", "996",
//     "Kyrgyzstan"],
//    , "[LA", "856",
//     "Laos"],
//    , "[LV", "371",
//     "Latvia"],
//    , "[LB", "961",
//     "Lebanon"],
//    , "[LS", "266",
//     "Lesotho"],
//    , "[LR", "231",
//     "Liberia"],
//    , "[LY", "218",
//     "Libya"],
//    , "[LI", "417",
//     "Liechtenstein"],
//    , "[LT", "370",
//     "Lithuania"],
//    , "[LU", "352",
//     "Luxembourg"],
//    , "[MO", "853",
//     "Macao"],
//    , "[MK", "389",
//     "Macedonia"],
//    , "[MG", "261",
//     "Madagascar"],
//    , "[MW", "265",
//     "Malawi"],
//    , "[MY", "60",
//     "Malaysia"],
//    , "[MV", "960",
//     "Maldives"],
//    , "[ML", "223",
//     "Mali"],
//    , "[MT", "356",
//     "Malta"],
//    , "MH[", "692",
//     Marshall "Islands"],
//    , "[MQ", "596",
//     "Martinique"],
//    , "[MR", "222",
//     "Mauritania"],
//    , "[YT", "269",
//     "Mayotte"],
//    , "[MX", "52",
//     "Mexico"],
//    , "[FM", "691",
//     "Micronesia"],
//    , "[MD", "373",
//     "Moldova"],
//    , "[MC", "377",
//     "Monaco"],
//    , "[MN", "976",
//     "Mongolia"],
//    , "[ME", "382",
//     "Montengro"],
//    , "[MS", "1664",
//     "Montserrat"],
//    , "[MA", "212",
//     "Morocco"],
//    , "[MZ", "258",
//     "Mozambique"],
//    , "[MN", "95",
//     "Myanmar"],
//    , "[NA", "264",
//     "Namibia"],
//    , "[NR", "674",
//     "Nauru"],
//    , "[NP", "977",
//     "Nepal"],
//    , "[NL", "31",
//     "Netherlands"],
//    , "AN[", "599",
//     Netherlands "Antilles"],
//    , "NC[", "687",
//     New "Caledonia"],
//    , "NZ[", "64",
//     New "Zealand"],
//    , "[NI", "505",
//     "Nicaragua"],
//    , "[NE", "227",
//     "Niger"],
//    , "[NG", "234",
//     "Nigeria"],
//    , "[NU", "683",
//     "Niue"],
//    , "KP[", "850",
//     North "Korea"],
//    , "NF[", "672",
//     Norfolk "Islands"],
//    , "NP[", "670",
//     Northern "Marianas"],
//    , "[NO", "47",
//     "Norway"],
//    , "[OM", "968",
//     "Oman"],
//    , "[PK", "92",
//     "Pakistan"],
//    , "[PW", "680",
//     "Palau"],
//    , "[PS", "970",
//     "Palestine"],
//    , "[PA", "507",
//     "Panama"],
//    , "PG", ["675",
//     Papua New "Guinea"],
//    , "[PY", "595",
//     "Paraguay"],
//    , "[PE", "51",
//     "Peru"],
//    , "[PH", "63",
//     "Philippines"],
//    , "[PN", "64",
//     "Pitcairn"],
//    , "[PL", "48",
//     "Poland"],
//    , "[PT", "351",
//     "Portugal"],
//    , "PR[", "1787",
//     Puerto "Rico"],
//    , "[QA", "974",
//     "Qatar"],
//    , "CG", "24[2",
//     Republic of the "Congo"],
//    , "[RE", "262",
//     "Reunion"],
//    , "[RO", "40",
//     "Romania"],
//    , "[RU", "7",
//     "Russia"],
//    , "[RW", "250",
//     "Rwanda"],
//    , "BL[", "590",
//     Saint "Barthelemy"],
//    , "SH[", "290",
//     Saint "Helena"],
//    , "KN", "1869", [
//     Saint Kitts & amp; "Nevis"],
//    , "SC[", "1758",
//     Saint "Lucia"],
//    , "[SR", "597",
//     "Suriname"],
//    , "MF[", "590",
//     Saint "Martin"],
//    , "PM", "508", [
//     Saint Saint Pierre and "Miquelon"],
//    , "VC", "1784", [
//         Saint Vincent and the "Grenadines"],
//    , "[WS", "685",
//     "Samoa"],
//    , "SM[", "378",
//     San "Marino"],
//    , "ST", "239", [
//     Sao Tome & amp; "Principe"],
//    , "SA[", "966",
//     Saudi "Arabia"],
//    , "[SN", "221",
//     "Senegal"],
//    , "[CS", "381",
//     "Serbia"],
//    , "[SC", "248",
//     "Seychelles"],
//    , "SL[", "232",
//     Sierra "Leone"],
//    , "[SG", "65",
//     "Singapore"],
//    , "SX[", "1721",
//     Sint "Maarten"],
//    , "[SK", "421",
//     "Slovakia"],
//    , "[SI", "386",
//     "Slovenia"],
//    , "SB[", "677",
//     Solomon "Islands"],
//    , "[SO", "252",
//     "Somalia"],
//    , "ZA[", "27",
//     South "Africa"],
//    , "KR[", "82",
//     South "Korea"],
//    , "SS[", "211",
//     South "Sudan"],
//    , "[ES", "34",
//     "Spain"],
//    , "LK[", "94",
//     Sri "Lanka"],
//    , "[SD", "249",
//     "Sudan"],
//    , "[SR", "597",
//     "Suriname"],
//    , "SJ", "47", [
//     Svalbard & amp; Jan "Mayen"],
//    , "[SZ", "268",
//     "Swaziland"],
//    , "[SE", "46",
//     "Sweden"],
//    , "[CH", "41",
//     "Switzerland"],
//    , "[SY", "963",
//     "Syria"],
//    , "[TW", "886",
//     "Taiwan"],
//    , "[TJ", "992",
//     "Tajikistan"],
//    , "[TZ", "255",
//     "Tanzania"],
//    , "[TH", "66",
//     "Thailand"],
//    , "[TG", "228",
//     "Togo"],
//    , "[TO", "676",
//     "Tonga"],
//    , "TT", "18[68",
//     Trinidad & amp; "Tobago"],
//    , "[TN", "216",
//     "Tunisia"],
//    , "[TR", "90",
//     "Turkey"],
//    , "[TM", "993",
//     "Turkmenistan"],
//    , "TC", "1649", [
//     Turks & amp; Caicos "Islands"],
//    , "[TV", "688",
//     "Tuvalu"],
//    , "[UG", "256",
//     "Uganda"],
//    , "[UA", "380",
//     "Ukraine"],
//    , "AE", ["971",
//     United Arab "Emirates"],
//    , "GB[", "44",
//     United "Kingdom"],
//    , "US[", "1",
//     United "States"],
//    , "[UY", "598",
//     "Uruguay"],
//    , "[UZ", "998",
//     "Uzbekistan"],
//    , "[VU", "678",
//     "Vanuatu"],
//    , "VA[", "379",
//     Vatican "City"],
//    , "[VE", "58",
//     "Venezuela"],
//    , "[VN", "84",
//     "Vietnam"],
//    , "WF", "68[1",
//     Wallis & amp; "Futuna"],
//    , "YE[", "969",
//     "Yemen "],
//    , "YE[", "967",
//     "Yemen "],
//    , "[ZM", "260",
//     "Zambia"],
//    , "[ZW", "263",
//     "Zimbabwe"],
//     </option,
//   </select,,
// ];
